from cProfile import label
import pandas as pd
from matplotlib import pyplot as plt

trainacc = pd.read_csv('trainacc.csv')
trainf1 = pd.read_csv('trainf1.csv')
trainloss = pd.read_csv('trainloss.csv')
trainp = pd.read_csv('trainp.csv')
trainr = pd.read_csv('trainr.csv')
valacc = pd.read_csv('valacc.csv')
valf1 = pd.read_csv('valf1.csv')
valloss = pd.read_csv('valloss.csv')
valp = pd.read_csv('valp.csv')
valr = pd.read_csv('valr.csv')

plt.figure()
plt.xlabel("epoch")
plt.title("accuracy")
plt.plot(trainacc.iloc[:, 2], color="blue", linewidth=2, label="train")
plt.plot(valacc.iloc[:, 2], color="red", linewidth=2, label="val")
plt.legend()
# plt.show()
plt.savefig('./t/acc.png')

plt.figure()
plt.xlabel("epoch")
plt.title("f1")
plt.plot(trainf1.iloc[:, 2], color="blue", linewidth=2, label="train")
plt.plot(valf1.iloc[:, 2], color="red", linewidth=2, label="val")
plt.legend()
# plt.show()
plt.savefig('./t/f1.png')

plt.figure()
plt.xlabel("epoch")
plt.title("recall")
plt.plot(trainr.iloc[:, 2], color="blue", linewidth=2, label="train")
plt.plot(valr.iloc[:, 2], color="red", linewidth=2, label="val")
plt.legend()
# plt.show()
plt.savefig('./t/recall.png')

plt.figure()
plt.xlabel("epoch")
plt.title("precision")
plt.plot(trainp.iloc[:, 2], color="blue", linewidth=2, label="train")
plt.plot(valp.iloc[:, 2], color="red", linewidth=2, label="val")
plt.legend()
# plt.show()
plt.savefig('./t/precision.png')

plt.figure()
plt.xlabel("epoch")
plt.title("train_loss")
plt.plot(trainloss.iloc[:, 2],  linewidth=2, label="train_loss")
plt.legend()
# plt.show()
plt.savefig('./t/trainloss.png')

plt.figure()
plt.xlabel("epoch")
plt.title("val_loss")
plt.plot(valloss.iloc[:, 2],  linewidth=2, label="val_loss")
plt.legend()
# plt.show()
plt.savefig('./t/valloss.png')
